export interface IArticle {
    idArticle?: number,
    acommander?: number,
    categorie?: String,
    codeBarres?: String,
    depot?: String,
    designation: String,
    expirable: boolean,
    famille?: String,
    inventaire: boolean,
    marque?: String,
    nomtech?: String,
    photo?: null,
    pmp?: number,
    prixachat?: number,
    prixpublic?: number,
    prixrevendeur?: number,
    prixspecial?: number,
    qteCarton: number,
    qtemax?: number,
    qtemin?: number,
    qteprevue?: number,
    qtestock?: number,
    reference: String,
    tva?: number,
    unite: String,
    utilise: boolean,
}
export interface ICF {
    idCF?: number,
    raisonSociale: String,
    tel: String,
    mail: String,
    solde: number,
}